GD-457 [FEAT] Fliplet Viewer Notifications Inbox
Fliplet/fliplet-widget-notification-inbox pull request #52
Opened 2023-09-22 10:54 UTC by hcarneiro

### Product areas affected

- Studio
  - Notifications Inbox component (Fliplet Viewer)

### What does this PR do?

- Modifies the existing notifications inbox component to work on Fliplet Viewer and be a copy of the [Studio Inbox](https://github.com/Fliplet/fliplet-studio/pull/7579).

### JIRA ticket

- https://weboo.atlassian.net/browse/GD-457

2023-09-22 16:49 UTC, tonytlwu requested changes

2023-09-22 16:49 UTC, tonytlwu commented on css/app/build.css
> +.notification-read .notification-badge {
What's this meant to do? Note that if there's a notification inbox in the app, the notification inbox will also have an `app/build.css` file on the page, which may be before/after this file.

2023-09-22 16:49 UTC, tonytlwu commented on css/build.css
> +[data-fliplet-viewer-notification-inbox-1-0-0-id] .notification .tags .tag + tag {
How have you tested this?

```suggestion
[data-fliplet-viewer-notification-inbox-1-0-0-id] .notification .tags .tag + .tag {
```

2023-09-22 16:49 UTC, tonytlwu commented on js/build.js
> +  Fliplet.Widget.register('FvNotificationInbox', function() {
```suggestion
  Fliplet.Widget.register('FVNotificationInbox', function() {
```

2023-10-10 10:40 UTC, tonytlwu requested changes

2023-10-10 10:40 UTC, tonytlwu commented on css/build.css
I only see two things on this file:

- Selector changes due to instance namespace
- New CSS declarations

Can you review everything in this file to make sure all the CSS declarations are necessary? For example, I see `[data-notification-status="draft"]` being used, but I'm certain user notifications will not support draft mode. That was only created for app notifications.

2023-10-10 10:48 UTC, hcarneiro commented on templates/notification.build.hbs
> +  <div class="tags">
You can see `data.tags` and there's a `each` loop in the template. You can also see above in the screenshot that the tags are being rendered.

2025-05-06 14:24 UTC, merged